# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
#image: mikk150/yii2-base:latest

# Select what we should cache between builds
cache:
  paths:
  - vendor/
before_script:
  - apt-get install -y libgmp-dev
  - docker-php-ext-install -j$(nproc) gmp
  - composer global require "fxp/composer-asset-plugin:^1.3.1"
  - composer install --prefer-dist

test:5.6:
  image: mikk150/yii2-base:5.6
  script:
    - vendor/bin/codecept run

test:7.0:
  image: mikk150/yii2-base:7.0
  script:
    - vendor/bin/codecept run
